
-- Drop the view that won't work for anon with security_invoker
DROP VIEW IF EXISTS public.nanny_profiles_public;

-- Create a security definer function for safe public nanny data
-- This exposes only safe fields, no email/phone/address
CREATE OR REPLACE FUNCTION public.get_public_nanny_profiles()
RETURNS TABLE(
  user_id uuid,
  full_name text,
  avatar_url text,
  languages text[],
  city text,
  country text,
  state text,
  years_of_experience integer,
  hourly_rate_spot numeric,
  hourly_rate_recurring numeric,
  babysitting_rate_chf numeric,
  part_time_childcare_rate_chf numeric,
  avg_rating numeric,
  total_reviews integer,
  bio text,
  ai_generated_description text,
  offers_date_night boolean,
  offers_overnight boolean,
  offers_after_school boolean,
  offers_weekend_holiday boolean,
  offers_full_time boolean,
  offers_part_time boolean,
  caregiver_types text[],
  has_first_aid boolean,
  has_cpr boolean,
  id_verified boolean,
  background_check_passed boolean,
  experience_infants boolean,
  experience_toddlers boolean,
  experience_preschool boolean,
  experience_school_age boolean,
  experience_teenagers boolean,
  experience_special_needs boolean,
  activities_offered text[],
  latitude numeric,
  longitude numeric,
  work_radius_km integer,
  gender text,
  nationality text,
  smoking_status text,
  can_drive boolean,
  has_drivers_license boolean,
  has_car boolean,
  comfortable_with_pets boolean,
  can_cook boolean,
  can_help_homework boolean,
  can_do_light_housekeeping boolean,
  has_early_childhood_cert boolean,
  has_child_psychology boolean,
  has_nutrition_cert boolean,
  has_montessori_cert boolean,
  education text,
  video_intro_url text,
  voice_intro_url text,
  profile_status text,
  currency text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 
    np.user_id,
    p.full_name,
    p.avatar_url,
    p.languages,
    np.city,
    np.country,
    np.state,
    np.years_of_experience,
    np.hourly_rate_spot,
    np.hourly_rate_recurring,
    np.babysitting_rate_chf,
    np.part_time_childcare_rate_chf,
    np.avg_rating,
    np.total_reviews,
    np.bio,
    np.ai_generated_description,
    np.offers_date_night,
    np.offers_overnight,
    np.offers_after_school,
    np.offers_weekend_holiday,
    np.offers_full_time,
    np.offers_part_time,
    np.caregiver_types,
    np.has_first_aid,
    np.has_cpr,
    np.id_verified,
    np.background_check_passed,
    np.experience_infants,
    np.experience_toddlers,
    np.experience_preschool,
    np.experience_school_age,
    np.experience_teenagers,
    np.experience_special_needs,
    np.activities_offered,
    np.latitude,
    np.longitude,
    np.work_radius_km,
    np.gender,
    np.nationality,
    np.smoking_status,
    np.can_drive,
    np.has_drivers_license,
    np.has_car,
    np.comfortable_with_pets,
    np.can_cook,
    np.can_help_homework,
    np.can_do_light_housekeeping,
    np.has_early_childhood_cert,
    np.has_child_psychology,
    np.has_nutrition_cert,
    np.has_montessori_cert,
    np.education,
    np.video_intro_url,
    np.voice_intro_url,
    np.profile_status,
    np.currency
  FROM public.nanny_profiles np
  JOIN public.profiles p ON p.user_id = np.user_id
  WHERE np.profile_visible = true
    AND np.profile_status = 'approved';
$$;
